steps:
  - id: "Activate virtual environment venv"
    name: 'gcr.io/cloud-function-371409/dataflow-python3:latest'
    entrypoint: '/bin/bash'
    args: [ '-c', 'source /venv/bin/activate' ]
    waitFor: ['-']

  - id: "Create dataflow template"
    name: 'gcr.io/cloud-function-371409/dataflow-python3:latest'
    entrypoint: 'python'
    args: [ 'df-task/function/main.py',
         "--job_name=dataflow-job",
         "--project=cloud-function-371409",
         "--region=us-central1",
         "--input_subscription=projects/cloud-function-371409/subscriptions/cf_pubsub_subscrp",
         "--output_table=cloud-function-371409:task_df_dataset.df_usual_messages_table",
         "--output_error_table=cloud-function-371409:task_df_dataset.df_error_messages_table",
         "--template_location=gs://cloud-function-371409-df-storage-bucket/template/dataflow-job",
         "--staging_location=gs://cloud-function-371409-df-storage-bucket/tmp",
         "--temp_location=gs://cloud-function-371409-df-storage-bucket/tmp",
         "--runner=DataflowRunner",
         "--setup_file='df-task/function/setup.py'",
         "--autoscaling_algorithm=NONE"
         ]
    waitFor: [
      'Activate virtual environment venv'
      ]